// Curated short common-English word list for passphrase generation.
// All words are 4-8 lowercase letters with no apostrophes or hyphens.
export const PASSPHRASE_WORDS: string[] = [
  "able", "above", "acid", "acorn", "actor", "adult", "after", "again", "agent", "agree",
  "ahead", "alarm", "album", "alert", "alike", "alive", "allow", "alone", "along", "alpha",
  "alter", "amber", "amend", "anchor", "angle", "ankle", "apart", "apple", "april", "arena",
  "argue", "armor", "array", "arrow", "asset", "atlas", "audio", "augur", "avoid", "awake",
  "award", "awful", "azure", "bacon", "badge", "baker", "balance", "ballad", "banana",
  "banjo", "barber", "barge", "barn", "basic", "basil", "basin", "batch", "beach", "beam",
  "bean", "bear", "beat", "beauty", "begin", "below", "berry", "beta", "bike", "bind",
  "bird", "black", "blade", "blank", "blast", "blend", "bless", "blind", "block", "blood",
  "bloom", "blue", "board", "boat", "body", "bold", "bonus", "book", "boost", "border",
  "bottle", "boulder", "bounce", "brain", "brake", "branch", "brand", "brass", "brave",
  "bread", "break", "breeze", "brick", "bridge", "brief", "bright", "broken", "bronze",
  "brook", "brown", "brush", "buddy", "budget", "build", "bulb", "bunch", "bundle",
  "burst", "butter", "cabin", "cable", "cactus", "cake", "calm", "camel", "camera", "candy",
  "canyon", "carbon", "card", "care", "carpet", "carry", "carve", "case", "cash", "castle",
  "catch", "cause", "cedar", "cell", "cement", "center", "chain", "chair", "chalk", "champ",
  "chance", "change", "channel", "chapter", "charge", "charm", "chart", "chase", "cheek",
  "cheer", "cheese", "chef", "chess", "chest", "chief", "chill", "chime", "chin", "chip",
  "choose", "chord", "chorus", "chunk", "cinema", "circle", "city", "civic", "claim", "clamp",
  "clarify", "clash", "class", "claw", "clay", "clean", "clear", "clever", "click", "client",
  "cliff", "climb", "clock", "close", "cloud", "clover", "club", "clue", "cluster", "coach",
  "coal", "coast", "coat", "cocoa", "code", "coffee", "coin", "cold", "color", "comet",
  "comic", "common", "copper", "coral", "corn", "corner", "cosmic", "cotton", "couch",
  "count", "country", "couple", "course", "cousin", "cover", "cow", "crack", "craft",
  "crane", "crash", "crater", "crazy", "cream", "create", "credit", "creek", "crew",
  "crisp", "crop", "cross", "crowd", "crown", "cruise", "crunch", "crystal", "cube", "cup",
  "curve", "cycle", "daily", "dairy", "dance", "dandy", "dare", "dark", "dash", "data",
  "date", "dawn", "dazzle", "deal", "debate", "decide", "deck", "deep", "deer", "defend",
  "delay", "delete", "delta", "demand", "denim", "depend", "depth", "desert", "design",
  "desk", "detail", "detect", "device", "dial", "diary", "dice", "diesel", "digit", "dinner",
  "dirt", "discuss", "dish", "divide", "doctor", "dodge", "dog", "dolphin", "donkey",
  "donor", "door", "draft", "drag", "drama", "draw", "dream", "dress", "drift", "drill",
  "drink", "drive", "drop", "drum", "duck", "dust", "duty", "dwell", "eagle", "early",
  "earth", "ease", "easy", "echo", "edge", "edit", "effect", "egg", "elbow", "elder",
  "elect", "elegant", "elf", "elite", "elm", "embed", "ember", "embrace", "emerald", "emit",
  "empty", "enable", "enact", "endure", "energy", "enforce", "engage", "engine", "enjoy",
  "enlist", "enrich", "enroll", "ensure", "enter", "entry", "envoy", "epoch", "equal",
  "equip", "erase", "erupt", "essay", "estate", "ethics", "evade", "evening", "event",
  "evolve", "exact", "exam", "exceed", "exhale", "exhibit", "exist", "exit", "expand",
  "expert", "expose", "extend", "fable", "fabric", "face", "fact", "factor", "faith",
  "falcon", "fall", "family", "fancy", "fan", "farm", "fashion", "fast", "father", "favor",
  "fear", "feast", "feather", "fee", "feed", "feel", "fence", "fern", "ferry", "festive",
  "fetch", "feud", "fever", "few", "fiber", "field", "fierce", "fifth", "fight", "figure",
  "film", "filter", "final", "find", "finger", "finish", "fire", "first", "fish", "fit",
  "fix", "flag", "flame", "flask", "flat", "flavor", "flesh", "flew", "flex", "flight",
  "flip", "float", "flock", "flood", "floor", "flour", "flow", "flower", "fluid", "flush",
  "fly", "foam", "focus", "foil", "fold", "folk", "follow", "food", "foot", "force",
  "forest", "forge", "forget", "forgive", "fork", "form", "fort", "forum", "fossil", "found",
  "fox", "frame", "free", "freeze", "fresh", "friend", "fringe", "frog", "front", "frost",
  "frown", "fruit", "fuel", "full", "fun", "funnel", "future", "fuzzy", "gadget", "gain",
  "galaxy", "gallop", "game", "gap", "garden", "garlic", "gasp", "gate", "gather", "gauge",
  "gaze", "gear", "gem", "general", "genius", "gentle", "ghost", "giant", "gift", "ginger",
  "giraffe", "girl", "give", "glad", "glance", "glass", "gleam", "glide", "glitter", "globe",
  "gloomy", "glory", "glove", "glow", "goal", "goat", "gold", "goose", "gorge", "govern",
  "gown", "grab", "grace", "grade", "grain", "grand", "grape", "grass", "gravity", "great",
  "green", "grid", "grief", "grim", "grin", "grip", "grit", "grocery", "groom", "ground",
  "group", "grove", "grow", "guard", "guess", "guest", "guide", "guilt", "guitar", "guppy",
  "habit", "hair", "half", "hall", "hammer", "hand", "happy", "harbor", "hard", "harvest",
  "hat", "haunt", "have", "hawk", "hay", "hazard", "head", "health", "heart", "heat",
  "heavy", "hedge", "height", "helm", "help", "hen", "herb", "hero", "hill", "history",
  "hobby", "hold", "hole", "hollow", "home", "honey", "honor", "hood", "hook", "hope",
  "horn", "horse", "host", "hotel", "hour", "house", "hover", "human", "humor", "hunt",
  "hurry", "ice", "icon", "idea", "idle", "image", "indoor", "ink", "input", "inquiry",
  "insect", "inside", "iris", "iron", "island", "issue", "ivory", "jacket", "jaguar", "jam",
  "jar", "jazz", "jelly", "jewel", "job", "join", "joke", "journey", "joy", "judge",
  "juice", "jump", "jungle", "junior", "jury", "keen", "keep", "kettle", "key", "kick",
  "kind", "king", "kiss", "kite", "kitten", "kiwi", "knee", "knife", "knight", "knit",
  "knock", "knot", "knowledge", "koala", "label", "labor", "lace", "ladder", "lake",
  "lamp", "land", "lane", "language", "lantern", "large", "laser", "last", "later",
  "laugh", "launch", "law", "lawn", "layer", "lazy", "leaf", "lean", "learn", "leather",
  "leave", "lecture", "left", "legend", "lemon", "lend", "length", "lens", "lesson",
  "letter", "level", "liberty", "lift", "light", "like", "lily", "lime", "line", "link",
  "lion", "list", "little", "live", "lizard", "load", "lobby", "local", "lock", "logic",
  "lonely", "long", "loop", "loud", "lounge", "love", "loyal", "luck", "lumber", "lunar",
  "lunch", "luxury", "lyrics", "machine", "magic", "magnet", "main", "major", "make",
  "mammal", "man", "mango", "manor", "many", "map", "maple", "marble", "march", "margin",
  "market", "mask", "mass", "master", "match", "matter", "meadow", "meal", "mean",
  "measure", "meat", "media", "melody", "melt", "member", "memory", "mention", "menu",
  "mercy", "merit", "merry", "mesh", "metal", "method", "middle", "midnight", "mild",
  "mile", "milk", "million", "mimic", "mind", "mine", "minor", "mint", "minute", "miracle",
  "mirror", "mission", "mist", "mix", "model", "modify", "moment", "money", "monkey",
  "month", "moon", "moose", "moral", "morning", "moss", "moth", "mother", "motion",
  "motor", "mountain", "mouse", "move", "movie", "much", "muddle", "music", "myth",
  "naive", "name", "nation", "native", "natural", "near", "neat", "neck", "need", "neon",
  "nephew", "nerve", "nest", "network", "never", "newly", "next", "nice", "night",
  "noble", "noise", "nominee", "noodle", "normal", "north", "nose", "note", "novel",
  "nuance", "number", "nurse", "nut", "nymph", "oak", "obey", "object", "oblige", "ocean",
  "odd", "offer", "office", "often", "olive", "omega", "onion", "online", "only", "onset",
  "open", "opera", "option", "orange", "orbit", "orchard", "order", "organ", "origin",
  "ornate", "other", "ounce", "outdoor", "outer", "output", "outside", "oven", "over",
  "owl", "own", "oxygen", "oyster", "ozone", "pact", "page", "paint", "pair", "palace",
  "palm", "panel", "panic", "panther", "paper", "parade", "parent", "park", "parrot",
  "party", "pass", "pasta", "patch", "path", "patient", "patrol", "pattern", "pause",
  "pave", "peace", "peach", "peak", "peanut", "pear", "pearl", "pebble", "pencil", "people",
  "pepper", "perfect", "permit", "person", "petal", "phantom", "phase", "phone", "phrase",
  "piano", "pick", "picture", "piece", "pigeon", "pillow", "pilot", "pine", "pink",
  "pioneer", "pipe", "pirate", "pitch", "pixel", "pizza", "place", "plain", "planet",
  "plant", "plastic", "plate", "play", "please", "pledge", "plot", "plug", "plum",
  "plunge", "pocket", "poem", "poet", "point", "polar", "polish", "polite", "pond",
  "pony", "pool", "popular", "portion", "position", "post", "potato", "pottery", "powder",
  "power", "prairie", "praise", "predict", "prefer", "prepare", "present", "press", "pretty",
  "prevent", "price", "pride", "prime", "print", "priority", "prism", "prison", "private",
  "prize", "problem", "process", "produce", "profile", "program", "project", "promote",
  "proof", "proper", "property", "prosper", "protect", "proud", "provide", "public",
  "pudding", "pull", "pulp", "pulse", "puppy", "purchase", "pure", "purpose", "puzzle",
  "pyramid", "quail", "quake", "quality", "quantum", "quarter", "queen", "quest",
  "question", "quick", "quiet", "quill", "quilt", "quirk", "quote", "rabbit", "raccoon",
  "race", "rack", "radar", "radio", "rail", "rain", "raise", "rally", "ramp", "ranch",
  "random", "range", "rapid", "rare", "rate", "rather", "ravine", "raven", "raw", "razor",
  "ready", "real", "reason", "rebel", "rebuild", "recall", "receipt", "record", "recycle",
  "reduce", "reflect", "reform", "refuge", "region", "regret", "regular", "reject",
  "relax", "release", "relevant", "relief", "rely", "remain", "remember", "remind", "remove",
  "render", "renew", "rent", "repeat", "replace", "report", "require", "rescue", "resemble",
  "resign", "resist", "resort", "resource", "respond", "result", "retire", "retreat",
  "return", "reveal", "review", "reward", "rhino", "rhythm", "ribbon", "rice", "rich",
  "ride", "ridge", "rifle", "right", "rigid", "ring", "ripple", "rise", "risk", "river",
  "road", "roast", "robot", "rock", "rocket", "rodent", "rogue", "roof", "room", "rope",
  "rose", "rotate", "rough", "round", "route", "royal", "ruby", "rude", "rug", "rule",
  "run", "runway", "rural", "rush", "saddle", "safe", "sail", "salad", "salmon", "salt",
  "same", "sample", "sand", "satisfy", "sauce", "save", "say", "scale", "scan", "scare",
  "scatter", "scene", "scheme", "school", "science", "scissor", "scope", "score", "scorpion",
  "scout", "scrap", "screen", "script", "scrub", "sea", "search", "season", "seat", "second",
  "secret", "section", "secure", "seed", "seek", "segment", "select", "self", "sell", "send",
  "senior", "sense", "sentence", "series", "service", "set", "settle", "seven", "shade",
  "shadow", "shake", "shall", "shallow", "shape", "share", "shark", "sharp", "sheep",
  "sheet", "shelf", "shell", "shield", "shift", "shine", "ship", "shirt", "shoe", "shoot",
  "shore", "short", "shoulder", "shout", "show", "shrimp", "shrug", "shuffle", "shy",
  "side", "siege", "sight", "sign", "silent", "silk", "silver", "similar", "simple",
  "since", "sing", "siren", "sister", "site", "size", "skate", "sketch", "ski", "skill",
  "skin", "skirt", "skull", "slab", "slam", "sleep", "slender", "slice", "slide", "slight",
  "slim", "slogan", "slope", "slot", "slow", "slush", "small", "smart", "smile", "smoke",
  "smooth", "snake", "snap", "sneak", "snore", "snow", "soap", "soccer", "social", "sock",
  "soda", "soft", "solar", "soldier", "solid", "solution", "solve", "someone", "song",
  "soon", "sort", "soul", "sound", "soup", "source", "south", "space", "spare", "spark",
  "speak", "special", "speed", "spell", "spend", "sphere", "spice", "spider", "spike",
  "spin", "spirit", "split", "spoil", "sponsor", "spoon", "sport", "spot", "spread", "spring",
  "spy", "square", "squeeze", "squirrel", "stable", "stadium", "staff", "stage", "stairs",
  "stamp", "stand", "start", "state", "stay", "steak", "steel", "stem", "step", "stereo",
  "stick", "still", "sting", "stock", "stomach", "stone", "stool", "story", "stove", "strain",
  "strange", "stream", "street", "stretch", "strike", "string", "strong", "studio", "study",
  "stuff", "stumble", "style", "subject", "submit", "subway", "succeed", "such", "sudden",
  "suffer", "sugar", "suggest", "suit", "summer", "sun", "sunny", "super", "supply", "sure",
  "surface", "surprise", "surround", "survey", "suspect", "swallow", "swamp", "swap",
  "swarm", "sweat", "sweep", "sweet", "swift", "swim", "swing", "switch", "sword", "symbol",
  "symptom", "system", "table", "tackle", "tag", "tail", "talent", "talk", "tank", "tape",
  "target", "task", "taste", "tattoo", "taxi", "teach", "team", "tell", "ten", "tenant",
  "tennis", "tent", "term", "test", "text", "thank", "that", "thaw", "theme", "then",
  "theory", "there", "they", "thing", "this", "thought", "three", "thrive", "throw",
  "thumb", "thunder", "ticket", "tide", "tiger", "tilt", "timber", "time", "tiny", "tip",
  "tired", "tissue", "title", "toast", "tobacco", "today", "toddler", "toe", "together",
  "toilet", "token", "tomato", "tomorrow", "tone", "tongue", "tonight", "tool", "tooth",
  "top", "topic", "torch", "tornado", "tortoise", "toss", "total", "tourist", "toward",
  "tower", "town", "toy", "track", "trade", "traffic", "tragic", "train", "transfer", "trap",
  "trash", "travel", "tray", "treat", "tree", "trend", "trial", "tribe", "trick", "trigger",
  "trim", "trip", "trophy", "trouble", "truck", "true", "truly", "trumpet", "trust", "truth",
  "try", "tube", "tuition", "tumble", "tuna", "tunnel", "turkey", "turn", "turtle", "twelve",
  "twenty", "twice", "twin", "twist", "two", "typical", "ugly", "umbrella", "unable",
  "uncle", "under", "undo", "unfair", "unfold", "unhappy", "uniform", "unique", "unit",
  "universe", "unknown", "until", "unusual", "unveil", "update", "upgrade", "uphold",
  "upon", "upper", "upset", "urban", "urge", "usage", "use", "used", "useful", "useless",
  "usual", "utility", "vacant", "vacuum", "vague", "valid", "valley", "valve", "van",
  "vanish", "vapor", "various", "vast", "vault", "vehicle", "velvet", "vendor", "venture",
  "venue", "verb", "verify", "version", "very", "vessel", "veteran", "viable", "vibrant",
  "vicious", "victory", "video", "view", "village", "vintage", "violin", "virtual", "virus",
  "visa", "visit", "visual", "vital", "vivid", "vocal", "voice", "void", "volcano", "volume",
  "vote", "voyage", "wage", "wagon", "wait", "walk", "wall", "walnut", "want", "warfare",
  "warm", "warrior", "wash", "wasp", "waste", "water", "wave", "way", "wealth", "weapon",
  "wear", "weather", "web", "wedding", "weekend", "weird", "welcome", "west", "wet",
  "whale", "what", "wheat", "wheel", "when", "where", "whip", "whisper", "white", "whole",
  "wide", "width", "wife", "wild", "will", "win", "window", "wine", "wing", "wink", "winner",
  "winter", "wire", "wisdom", "wise", "wish", "witch", "with", "withdraw", "witness",
  "wolf", "woman", "wonder", "wood", "wool", "word", "work", "world", "worry", "worth",
  "wrap", "wreck", "wrestle", "wrist", "write", "wrong", "yard", "year", "yellow", "you",
  "young", "youth", "zebra", "zero", "zone", "zoo",
];

export const PASSPHRASE_SEPARATORS = ["-", ".", "_", " "];
